plugins {
    id 'java'
}

group = 'com.udemy.patterns'
version = '1.0.0'
description = 'Udemy - Design Patterns on Java'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}